# (PART) 2부: 기초 {-}

# 데이터로부터 학습하기: 로드맵 {#roadmap}

:::: {.infobox .tlverse data-latex=""}
:::{.center data-latex=""}
**학습 목표**
:::

1. 과학적 질문을 통계적 질문으로 번역합니다.
2. 데이터를 생성한 과학적 실험이나 연구에 대한 지식을 바탕으로 통계 모델을 정의합니다.
3. 관찰된 데이터 분포의 함수로서 인과적 매개변수를 식별합니다.
4. 독립적이고 동일하게 분포된(i.i.d.), 일관성, 측정되지 않은 교란 없음, 간섭, 적극성이라는 통계적 및 인과적 가정과 그 함의를 설명합니다.
::::

## 소개 {-}

통계적 학습의 로드맵은 실제 과학적 질문을 관련 통계적 추론 문제를 공식화하는 데 필요한 수학적 형식주의로 변환하는 과정과 관련이 있습니다.
여기에는 데이터를 (자체적인 기본 확률 분포를 가진) 확률 변수로 보고, 통계 모델 선택에 과학적 지식을 통합하고, 관심 있는 과학적 질문에 대한 답을 나타내는 통계적 목표 매개변수를 선택하고, 통계적 추정량의 효율적인 추정기를 개발하는 것이 포함됩니다.

## 로드맵 {#roadmap-steps}

로드맵은 6단계 과정입니다.

1. 데이터를 확률 분포를 가진 확률 변수로 정의합니다, $O \sim P_0$
2. $P_0 \in \M$이 되도록 통계 모델 $\M$을 현실적으로 지정합니다.
3. 관심 있는 과학적 질문을 통계적 목표 매개변수 $\Psi$로 변환하고 목표 모집단을 설정합니다.
4. 현실적인 $\M$ 하에서 $\Psi$에 대한 추정기 $\hat{\Psi}$를 선택합니다.
5. 추정치 $\hat{\Psi}(P_n)$에 대한 불확실성 측도를 구성합니다.
6. 실질적인 결론을 내립니다.

### (1) 데이터: 확률 분포를 가진 확률 변수, $O \sim P_0$ {-}

우리가 마주하는 데이터셋은 과학적 (또는 자연적) 실험 결과의 모음입니다. 우리는 데이터를 _확률 변수_로 볼 수 있습니다. 즉, 동일한 실험이 반복된다면 해당 실험을 지배하는 동일한 기본 법칙에 의해 생성된 데이터의 다른 실현을 보게 될 것입니다. 특히, 실험이 여러 번 반복된다면 데이터를 생성하는 기본 확률 분포 $P_0$가 드러날 것입니다. 단일 단위 $O$에 대한 관찰된 데이터는 이 확률 분포 $P_0$에서 추출된 것으로 생각할 수 있습니다. 대부분의 경우, 우리 데이터셋에는 확률 변수 $O$의 $n$개의 _독립적이고 동일하게 분포된_ (i.i.d.) 관찰값이 있습니다. 그러면 관찰된 데이터는 $O_1, \ldots, O_n$의 모음이며, 여기서 아래 첨자는 개별 관찰 단위를 나타냅니다. 모든 데이터가 i.i.d.인 것은 아니지만, 이는 응용 데이터 분석에서 확실히 가장 일반적인 경우입니다. 비 i.i.d. 데이터를 처리하기 위한 여러 기술이 있으며, 여기에는 일부 변수(예: 반복 측정 데이터의 경우 피험자 ID)에 대해 조건부 독립성을 설정하여 i.i.d. 가정이 유지되도록 하는 것과 반복되거나 군집된 관찰에 대한 추론적 수정을 통합하는 것 등이 있습니다.

#### 경험적 확률 측정, $P_n$ {-}

$n$개의 i.i.d. 관찰값을 가지고 경험적 확률 측정 $P_n$을 정의할 수 있습니다. 경험적 확률 측정은 실제 확률 측정 $P_0$의 근사치이며, 관찰된 데이터로부터 학습할 수 있게 해줍니다. 예를 들어, 변수 집합, скажем $W$에 대한 경험적 확률 측정을 $W$에 속하는 관찰값의 비율로 정의할 수 있습니다. 즉,
\begin{equation*}
  P_n(W) = \frac{1}{n}\sum_{i=1}^{n} \I(O_i \in W)
\end{equation*}

특정 데이터셋에서 학습할 수 있는 범위를 이해하기 위해 다음으로 *"데이터 생성으로 이어진 프로세스에 대해 우리가 무엇을 알고 있는가?"*라는 질문을 해야 합니다. 이것이 우리를 2단계로 이끌어줍니다.

### (2) $P_0 \in \M$이 되도록 통계 모델 $\M$ 정의하기 {-}

통계 모델 $\M$은 관찰된 데이터가 생성된 프로세스를 설명할 수 있는 모든 가능한 확률 분포의 집합이며, 배경 과학적 지식에 의해 적절하게 제한됩니다. 종종 $\M$은 $P_0$에 대한 통계적 지식이 제한적이라는 사실을 반영하여 필연적으로 매우 큽니다(즉, 비모수적).

$P_0$가 유한한 수의 매개변수로 설명되는 경우 통계 모델은 _모수적_이라고 합니다. 이러한 가정은 예를 들어 $O$가 평균 $\mu$와 분산 $\sigma^2$를 갖는 정규 분포를 갖는다는 제안에 의해 이루어집니다. 보다 일반적으로 모수적 모델은 다음과 같이 정의될 수 있습니다.

\begin{equation*}
  \M(\theta) = \{P_{\theta} : \theta \in \R^d \},
\end{equation*}
이는 일부 유한한 $d$차원 매개변수 $\theta$로 색인된 모든 분포 $P_{\theta}$로 구성된 제한된 통계 모델을 설명합니다.

$P_0$가 특정 모수적 형태를 갖는다는 가정은 매우 일반적으로 이루어집니다. 불행히도 이러한 가정이 데이터 생성 프로세스에 대한 영역 지식에 의해 뒷받침되지 않는 경우에도 마찬가지입니다. 현재 및 전통적인 통계 데이터 분석 문화에서 이러한 과도한 단순화 관행은 일반적으로 당면한 과학적 질문에 안정적으로 답하려는 모든 시도를 복잡하게 만들거나 완전히 좌절시킵니다. 왜냐고요? 주어진 데이터셋의 기본 데이터 생성 분포가 실제로 정규 분포에서 널리 사용되는 것처럼 단 두 개의 매개변수에 의해서만 지배된다는 것을 (의심의 여지 없이) _알기_ 위해 얼마나 많은 지식을 가져야 하는지 생각해 보십시오. 마찬가지로, 주항 콕스 비례 위험, 로지스틱 회귀 및 선형 모델은 매우 제한된 통계 모델을 의미하며, 가정 중 어느 하나라도 부당한 경우 치료가 무작위화된 경우를 제외하고는 결과에 편향이 발생합니다. 모수적 가정을 정당화하는 데 사용되는 철학은 "모든 모델은 틀렸지만 일부는 유용하다"는 조지 박스의 자주 인용되는 말에 대한 잘못된 해석에 뿌리를 두고 있으며, 이는 데이터 분석가가 임의적인 모델링 선택을 하도록 무책임하게 장려하는 데 사용되었습니다. 그러나 이러한 근거 없는 가정을 할 경우 $\M$이 $P_0$를 포함하지 않을 가능성이 더 높으며, 이 경우 통계 모델이 잘못 지정되었다고 합니다. 통계 모델의 잘못된 지정은 오해의 소지가 있고 신뢰할 수 없는 결과와 추론으로 이어지는 편향을 야기합니다.

부당한 가정과 과도한 단순화의 결과는 동일한 과학적 문제에 대해 현저하게 다른 답변이 나오는 통계 데이터 과학의 관행입니다. 실질적으로 이는 서로 다른 데이터 분석가가 (잘 전달되지 않은) 서로 다른 모델링 결정과 가정 하에 서로 다른 통계 기법을 적용하기 때문입니다. 통계 데이터 분석의 초기 단계에서도 "잘못된 질문에 대한 정확한 답보다... 올바른 질문에 대한 근사적인 답을 개발하는 것이 훨씬 낫다"[@tukey1962future]고 인식되었지만, 전통적인 통계는 수십 년 동안 이 조언을 무시했습니다 [@donoho2017fifty]. 로드맵은 관찰된 데이터의 기본이 되는 실제 데이터 생성 분포를 표현하여 통계 모델을 정의함으로써 이러한 편향을 피합니다. 궁극적인 목표는 (사용 가능한 과학적 지식에 의해 부과된 제약까지) 통계적 추정 문제를 _정확하게_ 공식화하여 동기를 부여하는 과학적 문제에 맞게 추정 절차를 조정할 수 있도록 하는 것입니다.

영역 과학자(들)가 데이터를 생성한 프로세스/실험에 대해 _실제로 알려진_ 내용에 대해 절대적으로 명확하게 이해하고 이를 가능한 한 자세하게 데이터 과학자에게 전달하는 것이 중요합니다. 이 지식은 거의 실질적인 진리가 아니라 과학적 관습, 수용된 가설 및 운영 가정의 형태로 제공됩니다.
<!--
rp: 이것은 모호합니다. M에 통합될 과학적 관습, 수용된 가설 및 운영 가정의 예는 무엇입니까?
-->
그런 다음 영역 지식을 $P_0$에 대한 통계적 지식으로 변환하고, $P_0$에 대해 알려진 것을 존중하고 더 이상 제한을 두지 않도록 통계 모델 $\M$을 정의하는 것은 데이터 과학자의 책임입니다. 이러한 방식으로 $P_0$가 $\M$에 포함되도록 보장할 수 있으며, 이를 일반적으로 _현실적인_ 통계 모델 $\M$을 정의한다고 합니다.

$\M$을 현실적으로 정의하려면 통계적 문제 해결 패러다임의 전환이 필요합니다. 익숙한 방법/소프트웨어를 고려한 다음 해당 도구 상자로 대부분의 문제를 해결하려고 하는 대신, 먼저 실험과 과학적 질문에 대한 깊은 이해를 얻은 다음 이를 존중하는 방식으로 데이터로부터 학습하기 위한 계획을 수립해야 합니다. 이를 위해서는 통계학자가 탄탄한 방법론적 및 이론적 기초뿐만 아니라 우수한 의사소통 기술을 갖추어야 합니다. 일반적으로 연구 세부 정보를 검토하고, 관심 질문을 구체화하고, 기술적 세부 정보를 번역하고, 통계적으로 정확하고 비통계학자 영역 전문가와 합의할 수 있는 방식으로 결과를 해석하기 위해 영역 전문가와 여러 차례 회의가 필요하기 때문입니다. 불행히도 통계학자와 비통계학자 연구원 간의 의사소통은 종종 잘못된 해석으로 가득 차 있습니다. 각자 고유한 전문 지식을 가지고 있으므로 이는 예상되는 일이지만, 기본 과학과 동기를 부여하는 연구에 대한 적절한 의사소통은 각자가 특정 통계 데이터 분석에 대한 적절한 맥락을 갖도록 보장하는 데 도움이 될 수 있습니다. 로드맵은 데이터로부터 현실적으로 학습하기 위한 원칙적인 메커니즘을 제공하므로 데이터로부터 학습한 내용이 관심 있는 과학적 질문에 대한 답변의 신뢰할 수 있고 재현 가능한 근사치를 나타냅니다. 로드맵은 과학적 지식과 질문을 데이터로부터 학습하는 데 사용할 수 있는 통계적 프레임워크로 변환하는 엄격한 방법을 제공하므로 통계학자와 비통계학자 영역 과학자 간의 의사소통을 안내하는 귀중한 도구입니다. 이것이 로드맵의 다음 단계인 *"데이터로부터 무엇을 배우려고 하는가?"*로 이어집니다.

### (3) 통계적 목표 매개변수 $\Psi$와 통계적 추정량 $\psi_0$ {-}

통계적 목표 매개변수 $\Psi$는 통계 모델 $\M$에서 매개변수 공간으로의 매핑으로 정의됩니다. 일반적으로 매개변수 공간은 실수이지만(반드시 그런 것은 아님), 이 경우 목표 매개변수를 매핑 $\Psi: \M \rightarrow \R$로 공식적으로 정의할 수 있습니다. 통계적 추정량은 데이터로부터 배우고자 하는 양, 즉 특정 목표 모집단에 대한 잘 정의된(종종 인과적인) 관심 질문에 대한 답변을 나타내는 것으로 볼 수 있습니다. 일반적인 통계적 추정량과 달리 인과적 추정량은 _관찰된 데이터로부터의 식별_을 허용하기 위해 추가적인 가정 집합이 필요합니다. 인과 모델[@pearl2009causality; @hernan2022causal]을 기반으로 하는 식별 가정은 테스트할 수 없으며 연구 중인 시스템 또는 실험이 수행된 프로세스에 대한 지식의 조합을 통해 정당화되어야 합니다. 이러한 가정은 [인과적 목표 매개변수](#causal)에 대한 다음 섹션에서 자세히 설명합니다.

간단한 예로, 모든 성인에 대한 생존 시간 관찰값을 포함하는 데이터셋을 생각해 보십시오. 여기서 우리의 관심 질문은 "성인이 5년 이상 살 확률은 얼마인가?"입니다. 우리는 다음을 갖습니다.

\begin{equation*}
  \psi_0 = \Psi(P_0) = \E_{P_0}(O > 5) = \int_5^{\infty} dP_0(o).
\end{equation*}

이 질문에 대한 답은 **통계적 추정량, $\Psi(P_0)=\psi_0$**이며, 이것이 우리가 데이터로부터 배우고자 하는 양입니다. 위에서 논의한 바와 같이, $\M$을 현실적으로 정의하고, 질문이 데이터에서 지원되도록 $\Psi$와 목표 모집단을 확정하기 위해서는 영역 과학자와 통계학자 간의 반복적인 의사소통이 종종 필요합니다. 예를 들어, 성인의 편두통 치료를 위한 두통약의 평균 효과를 배우는 데 관심이 있고 고혈압이 있는 사람은 약을 받을 수 없다는 것을 알게 되었다고 가정해 봅시다. 다음 영역 과학자와의 회의에서 목표 모집단을 고혈압이 없는 성인으로 수정하거나 $\Psi$ 내에서 고혈압이 있는 성인은 치료를 받을 수 있는 개인으로 간주되지 않는 동적 치료와 관련된 질문을 할 것을 제안할 수 있습니다. $O$, $\M$을 현실적으로 정의하고 $\Psi$를 정의하면 통계적 추정 문제를 공식적으로 정의한 것입니다. 다음은 4단계입니다. "_데이터로부터 관심 질문에 대한 근사적인 답을 어떻게 배울 수 있는가?_"

### (4) 추정기 $\hat{\Psi}$와 추정치 $\psi_n$ {-}

통계적 추정량의 좋은 근사치를 얻으려면 추정기 $\hat{\Psi}$가 필요합니다. 이는 가능한 경험적 분포 $P_n$(비모수적 통계 모델 $\M_{NP}$에 존재)의 집합에서 관심 있는 목표 매개변수의 매개변수 공간으로의 매핑으로 정의된 _사전_ 지정 알고리즘입니다. $\hat{\Psi} : \M_{NP} \rightarrow \R$. 즉, $\hat{\Psi}$는 관찰된 데이터, 즉 $P_n$의 실현을 입력으로 받아 매개변수 공간의 값을 출력하는 함수입니다. 추정기는 관찰된 데이터의 해당 경험적 분포를 매개변수 공간의 값으로 매핑하는 연산자로 볼 수 있으며, 이러한 함수에 의해 생성된 숫자 출력은 **추정치, $\hat{\Psi}(P_n)=\psi_n$**입니다. 따라서 $\psi_n$은 관찰된 데이터 $O_1, \ldots, O_n$의 경험적 확률 분포 $P_n$에 의해 알려진 매개변수 공간의 요소입니다. 확률 변수 $O$의 표본 크기 $n$을 기반으로 $P_n$의 실현을 대입하면 실제 매개변수 값 $\psi_0$의 추정치 $\psi_n$을 얻습니다.
<!--
nh: $\hat{\Psi}(\cdot)$의 사용은 근사 매핑을 의미하는 것 같습니다. 즉, $\hat{\Psi}(\cdot)$는 $\Psi()$가 아닙니다. 마치 매핑 $\Psi(\cdot)$로 표현된 질문의 근사 버전에 답하는 것처럼 들립니다.

rp: 예, $\hat{\Psi}$를 사용하여 $\Psi$를 근사하고 있습니다. $\hat{\Psi}$는 $\Psi$의 추정기입니다.
-->
2단계에서 동기를 부여했듯이 추정을 위해 현실적인 통계 모델을 고려하는 것이 필수적입니다. 따라서 데이터 생성 프로세스의 일부를 제한하지 않도록 하는 유연한 추정기가 필요합니다. 준모수 이론과 경험적 프로세스 이론은 현실적인 통계 모델에서 유연한 추정 전략에 의존하는 추정기의 동작을 구성, 벤치마킹 및 이해하기 위한 프레임워크를 제공합니다. 일반적으로 추정기의 바람직한 속성은 규칙적인 점근적 선형(RAL)이고 효율적이어서 최소 분산을 갖는 정규 극한 분포를 허용한다는 것입니다. 대체/대입 RAL 추정기도 장점이 있습니다. $\M$의 범위 내에 머무르는 것이 보장되며, 대입이 아닌 추정기에 비해 유한 표본에서 편향과 분산이 개선됩니다. 이론과 이러한 속성에 대한 심층적인 논의는 문헌[예: @kennedy2016semiparametric; @vdl2011targeted]에서 확인할 수 있습니다. 다음 단계에서 몇 가지 주요 개념을 검토합니다.

목표 매개변수 추정치의 불확실성을 정량화하기 위해, 통계적 추론 수행 과정의 일부로서 추정기의 표본 분포에 대한 이해가 필요합니다. 이것이 5단계로 이어집니다. "_과학적 질문에 대한 통계적 답변에 얼마나 확신해야 하는가?_"

### (5) 추정치 $\psi_n$에 대한 불확실성 측정 {-}

추정기 $\hat{\Psi}$는 경험적 분포 $P_n$의 함수이므로 추정기 자체는 표본 분포를 갖는 확률 변수입니다. 따라서 $n$개의 관찰값을 추출하는 실험을 반복하면 매번 다른 추정치 실현을 얻게 됩니다. 이러한 추정치의 가상 분포는 추정기의 표본 분포입니다.

추정기 구성의 주요 목표는 경험적 프로세스 이론을 포함하는 이론적 분석을 통해 점근적 표본 분포를 도출할 수 있도록 하는 것입니다. 이와 관련하여 우리가 초점을 맞추는 추정기의 중요한 속성은 점근적 선형성입니다. 특히, 점근적 선형성은 추정기와 목표 매개변수(즉, 실제값) 간의 차이가 점근적으로 i.i.d. 확률 변수의 평균과 점근적으로 무시할 수 있는 나머지 항으로 표현될 수 있음을 나타냅니다.

\begin{equation*}
  \hat{\Psi}(P_n) - \Psi(P_0) = \frac{1}{n} \sum_{i=1}^n IC(P_0)(O_i) +
    o_p(n^{-1/2}),
\end{equation*}
여기서 영향 곡선(IC)은 관찰된 데이터 $O$의 함수이지만 함수 자체는 기본 데이터 생성 분포 $P_0$에 의해 정의됩니다. 이 점근적 근사를 기반으로 중심 극한 정리를 사용하여 다음을 보일 수 있습니다.

\begin{equation*}
  \sqrt{n} \left(\hat{\Psi}(P_n) - \Psi(P_0)\right) \sim N(0, \sigma^2_{IC}),
\end{equation*}
여기서 $\sigma^2_{IC}$는 $IC(P_0)(O)$의 분산입니다. $\sigma^2_{IC}$의 추정치가 주어지면 고전적인 _점근적으로 정확한_ Wald 유형 신뢰 구간(CI) 및 가설 검정을 구성할 수 있습니다. 예를 들어, 표준 $(1 - \alpha)$ CI는 다음과 같은 형태를 갖습니다.

\begin{equation*}
  \psi_n \pm Z \frac{\hat{\sigma}_{IC}}{\sqrt{n}} \ ,
\end{equation*}
여기서 $Z$는 표준 정규 분포의 $(1 - \alpha / 2)^\text{th}$ 백분위수입니다. 관례에 따라 우리는 종종 95% 양측 CI를 구성하는 데 관심이 있으며, 이는 극한 분포의 각 꼬리에 확률 질량 $\alpha/2 = 0.025$에 해당합니다. 따라서 $Z \approx 1.96$을 백분위수로 사용합니다.

로드맵의 (1)-(5)단계는 통계 분석 계획을 정의하며, 이 모든 작업은 데이터가 공개되기 전에 수행될 수 있습니다. 로드맵의 마지막 단계는 (4)단계와 (5)단계에서 얻은 결과를 해석하는 것과 관련되므로 데이터 분석이 필요합니다. 그러나 (6)단계의 일부로 수행될 수 있는 추가 분석도 미리 지정할 수 있습니다. 로드맵의 이 마지막 단계는 "_연구 결과의 해석과 견고성은 무엇이며, 그로부터 어떤 결론을 도출할 수 있는가?_"라는 질문을 다룹니다.

### (6) 실질적인 결론 내리기 {-}

실질적인 결론을 내리는 것은 연구 결과를 해석하는 것을 포함합니다. 또한 나중에 다룰 수 있는 후속 질문을 하거나 향후 연구에 정보를 제공할 수 있는 문제를 논의할 기회를 제공합니다. 통계적 추정량 $\psi_0$는 통계적(비인과적) 및 인과적 해석을 가질 수 있습니다. 둘 다 종종 관심의 대상이며 제공될 수 있습니다. 순전히 통계적이든 인과적이든 해석에 관계없이 결과의 외삽을 줄이기 위해 목표 모집단을 해석에 명확하게 언급해야 합니다.

통계적 해석과 인과적 해석의 주요 차이점은 후자가 테스트할 수 없는 소위 "식별 가능성" 가정에 의존한다는 것입니다. 다음 섹션에서는 이러한 가정을 하나씩 검토합니다. 여기서는 연구 결과의 해석과 견고성에 중점을 둡니다. 구체적으로, 인과적 목표 매개변수는 추가적인 식별 가능성 가정 없이는 관찰된 데이터에서 추정할 수 없으므로 결과의 인과적 해석의 타당성은 데이터에서 이러한 가정이 유지되는지에 달려 있습니다. 이러한 가정이 유지되지 않을수록 _인과적 격차_, 즉 통계적 추정량과 인과적 추정량 간의 차이가 커집니다. 추적 관찰 손실이 없는 완벽한 무작위 대조 시험에서는 통계적 추정량과 인과적 추정량이 동일하므로 인과적 격차는 0이 됩니다. @diaz2013sensitivity에서는 추정치와 추론에 대한 가상 인과적 격차의 영향을 평가하기 위한 비모수적 민감도 분석이 제안됩니다. @gruber2022targeted 및 @gruber2022evaluating에는 @diaz2013sensitivity에서 제안된 방법의 예제 구현이 있습니다. 특히, 조정된 효과 추정치와 조정되지 않은 효과 추정치 간의 차이는 이 차이에 대한 가능한 인과적 격차 범위를 정의하는 데 사용됩니다. 관심 질문이 인과적인 경우 연구 결과의 견고성을 평가하기 위해 이러한 모델 없는 민감도 분석(다른 민감도 분석을 보완할 수 있음)을 권장합니다.

## 로드맵 요약 {#roadmap-summary}

$n$개의 i.i.d. 단위 $O_1, \ldots, O_n$에 걸쳐 수집된 데이터는 동일한 기본 확률 분포 $\P_0$에서 발생하는 확률 변수의 모음으로 볼 수 있습니다. 이는 데이터 모음을 $O_1, \ldots, O_n \sim P_0$로 생성된 것으로 표시하여 표현됩니다. 데이터를 생성한 실험에 대한 영역 지식(예: 치료가 무작위화되었는지, 치료 결정 또는 추적 관찰 손실이 공변량의 하위 집합에 의존했는지, 변수가 데이터에 추가된 시간 순서)은 통계학자/데이터 과학자가 통계 모델 $\M$을 정의하기 위해 변환하며, 이는 $P_0$를 포함해야 하는 후보 확률 분포의 가정된 공간입니다. 특히, 로드맵은 $P_0$가 그 안에 캡슐화되도록 보장하는 $\M$을 정의하는 중요한 역할을 강조합니다. $P_0 \in \M$. 실험(즉, 현실)에 대한 영역 지식에 기초하여 $\M$을 제한하는 것만으로(예: 주항 선형/로지스틱 모델과 같은 제한적인 함수 형식이 $P_0$를 설명한다고 가정하는 등 비현실적으로 제한하는 것과 반대로) $P_0 \in \M$을 보장할 수 있으며, 이를 현실적인 통계 모델 정의라고 합니다. 종종 $\M$을 제한하는 데 사용할 수 있는 지식은 매우 제한적이므로 $P_0 \in \M$이 되도록 $\M$을 매우 크게 정의해야 합니다. 따라서 현실적인 통계 모델은 유한 차원 매개변수 집합으로 색인화하기에는 너무 크기 때문에 준모수적 또는 비모수적이라고도 합니다. 필연적으로 우리의 통계적 질문은 "데이터로부터 무엇을 배우려고 하는가?"로 시작해야 하며, 이 질문에 대한 답은 실제 데이터 생성 분포 $P_0$에 의해 정의된 함수인 통계적 목표 매개변수 $\Psi$에 의해 포착되며, $\M$을 통계적 추정량 $\psi_0$으로 매핑합니다. 이 단계에서 통계적 추정 문제는 공식적으로 정의되어 데이터로부터 학습하여 관심 질문에 대한 답을 근사하는 알고리즘인 추정기 구성을 안내하기 위해 통계 이론을 사용할 수 있습니다. 추정기의 바람직한 속성은 편향되지 않고, 효율적이며, 대입 가능하고, 유한 표본에서 견고하다는 것입니다. 관심 질문이 인과적인 경우 다양한 가상 인과적 격차 하에서 연구 결과의 견고성을 평가하기 위해 모델 없는 민감도 분석을 권장합니다.

## 인과적 목표 매개변수 {#causal}

많은 경우, 우리는 할당된 치료(예: 처방약) 또는 "자연 발생" 노출(예: 인근 공장의 오염)과 같은 중재의 미래 관심 결과에 대한 _인과적 효과_에 관한 질문을 하는 문제에 관심이 있습니다. 이러한 인과적 효과는 대조적인 중재(예: 치료 조건과 비치료 조건 비교) 하에서 관심 모집단의 요약(예: 특정 결과의 모집단 평균)으로 정의될 수 있습니다. 예를 들어, 인과적 효과는 두 가지 _인과적 대조_, 즉 연구 모집단이 일부 오염 물질에 대해 균일하게 낮은 오염 수준을 경험하도록 설정된 가상 사례와 동일한 모집단이 동일한 오염 물질의 높은 수준을 균일하게 경험하도록 설정된 가상 사례 간의 질병 결과의 평균 차이로 정의될 수 있습니다.

이러한 관심 있는 인과적 대조를 설명하는 데 필요한 가상 데이터를 생성하는 이론적 실험을 운영하는 다양한 방법이 있습니다. 우리는 단순히 관심 있는 모든 치료 대조에 대해 가상 결과가 이론적으로 존재한다고 가정할 수 있으며[@neyman1938contribution; @rubin2005causal; @imbens2015causal], 이는 소위 "과학 표"에 인코딩될 수 있습니다. 또는 방향성 비순환 그래프(DAG)로 표현될 수 있는 구조적 인과 모델(SCM)[@pearl1995causal; @pearl2009causality]에 대한 중재를 고려할 수 있습니다. 두 프레임워크 모두 연구 중인 시스템의 변수 간의 알려지거나 가설화된 관계 집합을 인코딩하고 수학적으로 공식화할 수 있도록 합니다.

### 인과 모델 {-}

전반적으로 우리는 인과적 매개변수 설명을 위해 DAG와 SCM 사용에 초점을 맞출 것입니다. 표준적이지만 테스트할 수 없는 _식별 가능성_ 가정 하에서 이러한 인과적 매개변수에 해당하는 통계적 매개변수의 추정기는 아래에 소개됩니다. DAG는 연구 중인 시스템의 변수 간의 인과 관계에 대해 우리가 알고 있는 것을 시각적으로 표현하는 데 특히 유용한 도구입니다. 외인성 $U$ 항(아래 설명)을 무시하고 관찰된 데이터 $O$를 구성하는 변수의 다음 순서를 가정합니다. `DAGitty`[@textor2011dagitty]를 사용하여 DAG 구성을 아래에 시연합니다.

```{r simple-DAG, out.width = "60%"}
library(dagitty)
library(ggdag)

# 종속성 구조를 지정하여 DAG 만들기
dag <- dagitty("dag{
    W -> A ;
    W -> Y ;
    A -> Y ;
    W -> A -> Y ;
    W [confounders]
    A [exposure]
    Y [outcome]
  }")
tidy_dag <- tidy_dagitty(dag)

# DAG 시각화
ggdag(tidy_dag) +
  theme_dag()
```

위와 같은 DAG는 변수 간의 인과 관계를 표현하는 편리한 수단을 제공하지만, 이러한 동일한 인과 관계는 SCM으로 동등하게 표현될 수 있습니다.
$$\begin{align*}
  W &= f_W(U_W) \\
  A &= f_A(W, U_A) \\
  Y &= f_Y(W, A, U_Y),
\end{align*}$$
여기서 $f$는 DAG에서 해당 확률 변수의 "부모"(즉, 주어진 확률 변수로 화살표가 있는 업스트림 노드)와 관찰되지 않은 외인성 오차 항(즉, $U$)의 함수로서 해당 확률 변수를 생성하는 지정되지 않은 결정론적 함수입니다. SCM은 관심 모집단에서 데이터 $O$를 생성하는 알고리즘의 표현으로 생각할 수 있습니다. 통계 및 데이터 과학의 대부분은 이 방정식 시스템의 속성을 발견하는 데 전념합니다(예: 결과 변수 $Y$를 지배하는 함수 형태 $f_Y$ 추정).

<!--
여기서 $U_W$, $U_A$ 및 $U_Y$는 각 변수의 값에 영향을 미치는 측정되지 않은 외인성 배경 특성을 나타냅니다. NPSEM에서 $f_W$, $f_A$ 및 $f_Y$는 각 변수($W$, $A$ 및 $Y$ 각각)가 부모 및 측정되지 않은 배경 특성의 함수임을 나타내지만 특정 함수적 제약(예: 선형, 로지스틱-선형, 단일 상호 작용 등)이 부과되지 않는다는 점에 유의하십시오. 이러한 이유로 비모수적 구조 방정식 모델(NPSEM)이라고 합니다. DAG와 비모수적 구조 방정식 집합은 정확히 동일한 정보를 나타내므로 상호 교환적으로 사용할 수 있습니다.
-->

우리가 고려할 첫 번째 가상 실험은 전체 모집단에 노출을 할당하고 결과를 관찰한 다음 동일한 모집단에서 노출을 보류하고 결과를 관찰하는 것입니다. 이는 두 가지 서로 다른 중재 하에서 모집단의 결과 분포를 비교하는 것에 해당합니다.

1. 모든 개인에 대해 $A$가 $1$로 설정되고,
2. 모든 개인에 대해 $A$가 $0$으로 설정됩니다.

이러한 중재는 연구 중인 시스템의 구조 방정식에 대한 변경을 의미하는 작업으로 생각할 수 있습니다. $A = 1$의 경우 다음을 갖습니다.
$$\begin{align*}
  W &= f_W(U_W) \\
  A &= 1 \\
  Y(1) &= f_Y(W, 1, U_Y) \ ,
\end{align*}$$
반면, $A=0$의 경우,
$$\begin{align*}
  W &= f_W(U_W) \\
  A &= 0 \\
  Y(0) &= f_Y(W, 0, U_Y) \ .
\end{align*}$$

이러한 방정식에서 $A$는 더 이상 $W$의 함수가 아닙니다. 왜냐하면 시스템에 대한 중재가 수행된 중재와 일치하는 값 $1$ 또는 $0$ 중 하나로 $A$를 결정론적으로 설정했기 때문입니다. 새로운 기호 $Y(1)$과 $Y(0)$은 $f_Y$에 대한 $A$의 기여를 제거하고 대신 $A$를 각각 값 $1$과 $0$으로 설정하여 생성될 때 관심 모집단에서 결과 변수가 취할 값을 나타냅니다. 변수 $Y(1)$과 $Y(0)$은 종종 가상(사실과 반대되는 중재에서 발생하기 때문에)이라고 하며 다른 프레임워크에서는 $Y$의 _잠재적 결과_라고 합니다[@neyman1938contribution; rubin2005causal; imbens2015causal]. 이 두 중재 하에서 결과의 가상 평균의 차이는 가장 일반적으로 "평균 치료 효과"(ATE)라고 하는 잘 알려진 인과적 매개변수를 정의하며 다음과 같이 표시됩니다.

\begin{equation}
  ATE = \E_X[Y(1) - Y(0)],
  (\#eq:ate)
\end{equation}
여기서 $\E_X(\cdot)$는 이론적 (관찰 불가능한) 전체 데이터 (즉, $X = (W, Y(1), Y(0))$) 분포 $P_X$에 대해 취한 기대값입니다. 전체 데이터 구조 $X$는 정의상 관찰 불가능합니다. 왜냐하면 동일한 관찰 단위에 대해 $Y(1)$과 $Y(0)$을 모두 관찰할 수 없기 때문입니다.

동적 규칙(공변량 $W$의 함수에 따라 특정 중재를 할당함), 확률적 규칙(중재가 없는 경우 관찰된 $A$의 자연적인 값도 설명할 수 있음) 등을 기반으로 하는 중재와 같이 SCM에 대해 훨씬 더 복잡한 중재를 정의할 수 있습니다. 각각 다른 목표 인과적 매개변수를 생성하고 아래에서 논의되는 다른 식별 가능성 가정을 수반합니다.

### 식별 가능성 {-}

$A=0$일 때의 가상 결과인 $Y(0)$과 $A=1$일 때의 가상 결과인 $Y(1)$을 동시에 관찰할 수 없으므로 방정식 \@ref(eq:ate)에 나타나는 (ATE를 정의하는 기대값 $\E_X(\cdot)$ 내) 그 차이 $Y(1) - Y(0)$(개별 치료 효과)을 추정할 수 없습니다. 이를 _인과 추론의 근본 문제_라고 합니다[@holland1986statistics]. 따라서 인과 추론의 주요 활동 중 하나는 관심 있는 인과적 양을 관찰된 데이터의 데이터 생성 분포의 함수로 표현하는 데 필요한 가정을 _식별_하는 것입니다. 이를 위해 이러한 양이 관찰된 데이터 $O \sim P_0$와 해당 데이터 생성 분포 $P_0$에서 추정될 수 있는 가정을 만들어야 합니다. 다행히 위 SCM에 지정된 인과 모델이 주어지면 테스트할 수 없는 몇 가지 가정을 통해 관찰 데이터에서 ATE를 추정할 수 있습니다. 이러한 가정은 다음과 같이 요약할 수 있습니다.

::: {#consist-ass .definition name="일관성"}
단위 $i$에 대한 결과는 $A_i = a$일 때마다 $Y_i(a)$이며, 이는 "다른 버전의 치료 없음" 또는 "치료의 부작용 없음"으로 생각할 수 있습니다.
:::

::: {#interf-ass .definition name="간섭 없음"}
단위 $i$의 결과 $Y_i$는 모든 $i \neq j$에 대해 단위 $j$의 노출 $A_j$의 영향을 받을 수 없습니다.
:::

::: {#noconf-ass .definition name="측정되지 않은 교란 없음"}
모든 $a \in \mathcal{A}$에 대해 $A \perp Y(a) \mid W$이며, 이는 잠재적 결과 $(Y(a) : a \in \mathcal{A})$가 관찰된 공변량 $W$에 대해 조건부로 노출 상태 $A$와 독립적으로 발생함을 나타냅니다. 이는 자연 실험에서 발생하는 데이터의 _무작위화_ 가정과 유사하며, $W$가 둘 다에 영향을 미치더라도 $A$가 $Y$에 미치는 영향이 $W$가 $Y$에 미치는 영향과 분리될 수 있도록 보장합니다.
:::

::: {#posit-ass .definition name="적극성/중첩"}
$W$로 정의된 계층 전체에 걸쳐 관찰된 모든 단위는 치료를 받을 확률이 제한되어야 합니다. 즉, 모든 $a$와 $W$ 및 일부 $\epsilon > 0$에 대해 $\epsilon < \P(A = a \mid W) < 1 - \epsilon$) \ .
:::

기술적으로 말하면 SCM 프레임워크 내에서 작업할 때 이러한 가정 중 후자 두 가지만 필요하며, 처음 두 가지는 i.i.d. 데이터에 대한 SCM의 암시적 속성입니다(정말 궁금하다면 @pearl2010brief의 이 해설에서 자세한 논의를 참조하십시오). 우리는 네 가지 식별 가정을 모두 소개합니다. 왜냐하면 이들은 대부분 함께 고려되며 잠재적 결과 프레임워크 내에서 작업할 때 네 가지 모두 필요하기 때문입니다[@rubin2005causal; @imbens2015causal].

이러한 가정 하에서 ATE는 관찰된 데이터의 분포인 $P_0$의 함수로 다시 작성될 수 있습니다.

$$\begin{align}
  \psi_{\text{ATE}} &= \E_0[Y(1) - Y(0)] \\ \nonumber
                    &= \E_0 [\E_0[Y \mid A = 1, W] -
                       \E_0[Y \mid A = 0, W]] \ .
  (\#eq:estimand)
\end{align}$$
즉, ATE는 모집단에서 (모든 관찰값에 대해 평균을 냈을 때) 치료 조건($A = 0$ 대 $A = 1$)의 대조 하에서 각 피험자에 대한 예측된 결과 값의 평균 차이입니다. 따라서 이론적 완전 (또는 "전체") 데이터 분포의 매개변수는 관찰된 데이터 분포의 추정량으로 표현될 수 있습니다. 중요한 것은 방정식 \@ref(eq:estimand)의 표현에는 모수적 가정이 필요하지 않다는 것입니다. 따라서 우변의 회귀 함수는 기본 함수 형태에 대한 제한적인 가정 없이 추정될 수 있습니다. 다른 매개변수를 사용하면 잠재적으로 다른 식별 가능성 가정이 있을 수 있으며 결과 추정량은 $P_0$의 다른 구성 요소의 함수가 될 수 있습니다. 다음 장에서 몇 가지 더 복잡한 추정량을 논의합니다.

<!--
### 결측치 {-}

TODO: 마크에게 이것에 대한 메모를 추가하도록 요청하십시오.

-벤 (2022년 9월 20일)-
구체적인 방법론적 문제로서, 예를 들어 다중 대치 접근 방식과 비교하여 왜 중앙값/최빈값을 사용하여 대치합니까? 통계 검토관에게 이것이 미치는 영향에 대해 자문을 구하는 것이 좋습니다. 방법의 적절성에 관계없이 투명성을 위해 코호트 및 변수별 결측치 범위를 보여주는 표가 있어야 합니다. 또한 투명성을 위해 완전한 사례 분석을 민감도 분석으로 제시해야 합니다.

-마크 (2022년 9월 20일)-
예, 그것이 명확한 주장입니다. 즉, W*가 주어졌을 때 A가 Y_a와 독립적이면 결측치 문제가 없습니다. 여기서 W*는 모든 구성 요소 j에 걸쳐 W_j, Deltaj이며, Delta_j는 W_j가 측정되었음을 나타내는 지표입니다. 그러면 추정량은 E E(Y|A=1,W*)-E(Y|A=0,W*))이며 ATE와 같습니다. 이 가정이 위반되지만 특정 구성 요소 W_1에 대해서는 W*,W_1이 주어졌을 때 무작위화가 이루어지지만 W*가 주어지지 않았을 때는 그렇지 않다고 주장할 수 있다면 W_1을 결측 대상S으로 볼 수 있습니다. 이 경우 E_{W*,W_1} E(Y|A=1,W*,W_1)-E(Y|A=1,W*,W_1)을 배우고 싶지만 이는 아직 데이터 분포의 함수가 아닙니다. 따라서 W_1의 결측이 MAR이라고 가정해야 합니다. 예를 들어 결측 지표 Delta_{W_1}은 관찰된 Y와 A,W*의 함수이거나(예: 2단계 설계) 독립적인 노이즈를 넘어 W*,A만의 함수입니다. 그런 다음 이 양에 대한 원하는 식별 결과를 얻고 결과 TMLE를 개발할 수 있습니다. 또는 W_1이 측정된 세계에서 TMLE를 사용하고 역확률 결측 가중치(IPCW TMLE, 예: Rose, 2단계 설계에 대한 vdL)를 사용할 수 있습니다.

참고 문헌과 관련하여 ATE 식별 결과를 참조하고 W*가 주어졌을 때 이 RA 가정을 하는 것이 불합리하지 않다는 것을 분명히 하십시오. 또는 우려가 있는 경우에도 전체 W가 주어졌을 때 해결될 것이라고 생각할 특별한 이유가 없다는 것입니다. RA 가정이 위반되었다고 생각하고 만족스러운 소수의 W_1 전체 관찰값이 문제를 해결하지 못하면 민감도 분석에서 해결할 수 있습니다.

Neugebauer, Schnitzer, Petersen, Hubbard, Mertens 등 실제 데이터 분석을 포함하는 다양한 논문이 이미 이것을 수행했으며 따라서 참조될 수 있다고 생각합니다.

-벤 (2022년 9월 20일)-
마크의 철저한 설명에 관해서는, 우리가 단순히 다음과 같은 가정을 하는 것에 대해 편안하다고 생각합니다.
W*가 주어졌을 때 A가 Y_a와 독립적이면 결측치 문제가 없습니다. 여기서 W*는 모든 구성 요소 j에 걸쳐 W_j, Deltaj이며, Delta_j는 W_j가 측정되었음을 나타내는 지표입니다. 그러면 추정량은 E E(Y|A=1,W*)-E(Y|A=0,W*))이며 ATE와 같습니다.
-->
