project:
  type: book
  output-dir: _book

book:
  title: "tlverse와 함께하는 타겟 러닝(Targeted Learning)"
  author: "Mark van der Laan, Jeremy Coyle, Nima Hejazi, Ivana Malenica, Rachael Phillips, Alan Hubbard"
  date: "2026-03-26"
  language: ko
  chapters:
    - index.qmd
    - part: "1부: 예비 지식"
      chapters:
        - 01-intro.qmd
        - 02-tlverse.qmd
        - 03-data.qmd
    - part: "2부: 기초 이론"
      chapters:
        - 04-roadmap.qmd
        - 05-origami.qmd
        - 06-sl3.qmd
        - 07-tmle3.qmd
    - part: "3부: 심화 주제"
      chapters:
        - 08-tmle3mopttx.qmd
        - 09-tmle3shift.qmd
        - 10-tmle3mediate.qmd
        - 11-tmle3survival.qmd
    - references.qmd

bibliography: [book.bib, packages.bib]

format:
  html:
    theme: cosmo
    css: css/style.css
    toc: true
    include-before-body: html_extras/mathjax_header.html
