on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Render-PDF

jobs:
  build:
    name: build-bookdown
    runs-on: macOS-latest
    timeout-minutes: 360 # Relaxed timeout (default is often 360, but explicitly setting can prevent unexpected issues)
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KNITR_OPTIONS: "knitr.chunk.tidy=TRUE"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          # install nightly when checking on gh-pages
          pandoc-version: ${{ github.event.inputs.ghpages && 'nightly' || '2.17.1.1' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - name: Install OS dependencies
        run: |
          brew update
          brew install --cask xquartz
          brew install --cask calibre
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Install phamtomJS for webshot
        run: |
          webshot::install_phantomjs()
        shell: Rscript {0}

      - name: Cache bookdown results
        uses: actions/cache@v4
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-

      - name: Render book HTML
        run: |
          Rscript -e 'bookdown::clean_book(TRUE)'
          Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Render book PDF
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: tlverse-handbook-pdf
          path: _handbook/tlverse-handbook.pdf

      - name: Create Release and Upload PDF
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Changed 'master' to 'main'
        with:
          files: _handbook/tlverse-handbook.pdf
          tag_name: book-${{ github.sha }}
          name: "Book Release ${{ github.sha }}"
          body: "Automated book release including tlverse-handbook.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: _handbook
          path: _handbook/.
