on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: booklet

jobs:
  bookdown:
    name: build-bookdown
    runs-on: ubuntu-latest
    timeout-minutes: 60 # Relaxed timeout to 60 minutes (default is often 360, but explicitly setting can prevent unexpected issues)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          # Add build-essential to ensure core C/C++ development tools and headers are present
          sudo apt install -y curl libcurl4-doc libcurl4-openssl-dev \
            libharfbuzz-dev libfribidi-dev libmagick++-dev libpoppler-cpp-dev \
            texlive-extra-utils ghostscript build-essential

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install tinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.0'

      - name: Pre-install specific R dependencies
        run: |
          Rscript -e 'install.packages(c("cpp11", "systemfonts"), repos = "https://cloud.r-project.org")'
        # Adding a try-catch for robustness, as renv will handle it anyway later
        continue-on-error: true # Allow this step to fail without stopping the workflow

      - name: Install R dependencies via renv
        uses: r-lib/actions/setup-renv@v2


      - name: Cache bookdown results
        uses: actions/cache@v4
        with:
          path: _bookdown_files
          key: bookdown-2-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-2-

      - name: Render book HTML
        run: |
          Rscript -e 'bookdown::clean_book(TRUE)'
          Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'

      - name: Render book PDF
        run: |
          Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: tlverse-handbook-pdf
          path: _handbook/tlverse-handbook.pdf

      - name: Create Release and Upload PDF
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Changed 'master' to 'main'
        with:
          files: _handbook/tlverse-handbook.pdf
          tag_name: book-${{ github.sha }}
          name: "Book Release ${{ github.sha }}"
          body: "Automated book release including tlverse-handbook.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: _handbook
          path: _handbook/.
