name: Render Quarto Project and Release PDF

on:
  push:
    branches:
      - main

jobs:
  render-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest

      - name: Cache renv
        uses: actions/cache@v3
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R Dependencies via renv
        shell: bash
        run: |
          pixi run Rscript -e "install.packages('renv', repos = 'https://cloud.r-project.org')"
          pixi run Rscript -e "renv::restore()"

      - name: Render Quarto Project to PDF
        shell: bash
        run: |
          pixi run quarto render --to pdf --output-dir ./release_pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_pdf/index.pdf # Assuming index.pdf is created
          asset_name: tlverse-handbook-${{ github.run_number }}.pdf
          asset_content_type: application/pdf
